### ISSUE TITLE
Add support for external sources (currently we only support builtins)

### ISSUE THREAD

**Issue by Zeioth** [jay-babu/mason-null-ls.nvim#106]
## Problem
* We currently load builtins if they are installed.
* But we don't load external sources registered with `source` in `none-ls`. Look at the next example.

## Example
```lua
  {
    "nvimtools/none-ls.nvim",
    dependencies = {
      "jay-babu/mason-null-ls.nvim",
      "nvimtools/none-ls-extras.nvim",
    },
    event = "VeryLazy",
    opts = function()
      return {
        -- None-ls-extra sources
        sources = {
          require("none-ls.formatting.reformat_gherkin")   -- This is how we access a external sources (such as `none-ls-extras.nvim`)
          --require("null-ls").builtins.formatting.asmfmt  -- This is how we would normally access a builtin.
        },
        -- Attach the user lsp mappings to every none-ls client.
        on_attach = utils_lsp.apply_user_lsp_mappings
      }
    end
  },
```

* we don't need to manually load `asmfmt` because it is a builtin and mason-null-ls correctly auto load all builtins.
* but because `reformat_gherkin` is a external source, mason-null-ls is not able to load it, as it currently only look for builtins.

## Expected behavior
mason-null-ls should also detect sources from

* `none-ls.formatting.my_source`
* `none-ls.diagnostics.my_source`
* `none-ls.code_actions.my_source`
* `none-ls.completion.my_source`
* `none-ls.hover.my_source`

**Comment by jay-babu** [comment]
If I loop over everything registered in `none-ls.ACTION.SOURCE`, it should suffice? Will need to add de-duplication logic such that sources in both do not overlap

**Comment by jay-babu** [comment]
I am out of town for the next 2 weeks, if you have time to test this out before then, that would be great. If not, I will take a stab at it when I am back

**Comment by Zeioth** [comment]
That solution would be the same we do for builtins right? Yes I had the same in mind.

I've tried 
```
print(vim.inspect(require("none-ls.formatting")))
```

The problem is `none-ls` doesn't seem to be exposing it and it is not possible to iterate it. I'm gonna see if I can find a solution for that.

Enjoy your trip Jay. Let's see if I can manage some kind of PR.

**Comment by Zeioth** [comment]
I'd say it's done. You can check the fork here: https://github.com/Zeioth/none-ls-autoload.nvim

Please feel free to take it as reference and grab anything you want.

**Comment by jay-babu** [comment]
> I'd say it's done. You can check the fork here: https://github.com/Zeioth/none-ls-autoload.nvim
> 
> 
> 
> Please feel free to take it as reference and grab anything you want.

I would like to incorporate this into here. I just haven't been following anything none-ls has been doing. I've also switched using conform.nvim and nvim-lint which are so much nicer and faster hence I don't have an urge to figure out how this works. I looked at your repo and it just seems like one function to look copy over?

**Comment by Zeioth** [comment]
Yeah its just basically the function https://github.com/Zeioth/none-ls-autoload.nvim/blob/7b6358f1f03d95297d737c6ff141895845bc847c/lua/none-ls-autoload/utils.lua#L24 and the point we call it https://github.com/Zeioth/none-ls-autoload.nvim/blob/7b6358f1f03d95297d737c6ff141895845bc847c/lua/none-ls-autoload/utils.lua#L103

There is a project like mason-null for conform in case you'd like to contribute too:
https://github.com/frostplexx/mason-bridge.nvim
