### ISSUE TITLE
automatic_installation = { exclude } not working.

### ISSUE THREAD

**Issue by jasper-clarke** [jay-babu/mason-null-ls.nvim#107]
I'm trying to stop `phpactor` from being installed since I already have it locally installed. But the following is not working and it still is getting installed on start of neovim.

```lua
  {
    "jay-babu/mason-null-ls.nvim",
    config = function()
      require("mason-null-ls").setup({
        ensure_installed = nil,
        automatic_installation = { exclude = { "phpactor" } },
      })
    end,
  },
```

**Comment by jasper-at-windswept** [comment]
bump

**Comment by jay-babu** [comment]
Hey

`ensure_installed = {}`

What happens like this?

**Comment by jasper-at-windswept** [comment]
@jay-babu 
Still installs `phpactor` on start with that change.

**Comment by jasper-at-windswept** [comment]
bump

**Comment by jasper-at-windswept** [comment]
bump
This is still an issue please help.

**Comment by jay-babu** [comment]
do you see this line when it is installed? https://github.com/jay-babu/mason-null-ls.nvim/blob/main/lua/mason-null-ls/automatic_installation.lua#L67 @jasper-at-windswept

**Comment by jasper-at-windswept** [comment]
@jay-babu 
Yes if I have either `ensure_installed = {}` or `automatic_installation = { exclude = { "phpactor" } }`, uninstall `phpactor` via Mason, close Neovim and reopen it it shows me that message and installs it.

**Comment by jay-babu** [comment]
Is something else modifying the ensure installed list? Are you using a framework?

**Comment by jasper-at-windswept** [comment]
@jay-babu 
Nothing else is modifying it that I know.
I'm not using any framework, all my lsp configuration is here:
https://github.com/jasper-at-windswept/neovim/blob/main/lua/plugins/lsp-config.lua

**Comment by jay-babu** [comment]
If you set automatic installation to false, does it still happen?

**Comment by jasper-at-windswept** [comment]
It doesn't install anything then with `automatic_installation = false`
