### ISSUE TITLE
Editor config checker issues

### ISSUE THREAD

**Issue by asmodeus812** [jay-babu/mason-null-ls.nvim#37]
Hi, there seems to be a problem with the default config for the editor config checker and the executable name more specifically. Mason renames that executable to editor-checker but null ls expects by default it to be ec instead.

**Comment by jay-babu** [comment]
Hey, can you send a link to the null-ls portion you are talking about?

**Comment by asmodeus812** [comment]
Here you go, i did create a pr to change that this morning, if they are fine with it, the name will change to "ec"
https://github.com/williamboman/mason.nvim/blob/main/lua/mason-registry/editorconfig-checker/init.lua#L31

**Comment by asmodeus812** [comment]
Hi @jay-babu can you have a look at this pr - https://github.com/williamboman/mason.nvim/pull/722. Seems like it would be a better way to handle it here in this adapter plugin intead of mason.

**Comment by jay-babu** [comment]
> Hi @jay-babu can you have a look at this pr - https://github.com/williamboman/mason.nvim/pull/722. Seems like it would be a better way to handle it here in this adapter plugin intead of mason.

If null-ls says no, then I'm okay with fixing it here. This should be reported to the null-ls. I also verified that the tool should be called `editorconfig-checker`. I did this by building from source and the default binary name is as above. This looks like a mistake in the PR when it was originally introduced. `ec` is wrong and changes the convention

I can report this in 30 minutes or you can. Up to you

Thanks for the analysis and deep dive on this!

**Comment by asmodeus812** [comment]
@jay-babu I am okay if you can ping the nul ls authors to see what they say.

**Comment by jay-babu** [comment]
@asmodeus812 https://github.com/jose-elias-alvarez/null-ls.nvim/pull/1282

**Comment by jay-babu** [comment]
https://github.com/editorconfig-checker/editorconfig-checker/issues/232

the answer based on this discussion should resolve this discussion
