### ISSUE TITLE
Should the default setup function have something in it?

### ISSUE THREAD

**Issue by RoryNesbitt** [jay-babu/mason-null-ls.nvim#41]
I have added automatic setup in the order mason, null-ls, mason-null-ls as noted in your preferred method.

The two formatters which I have a specific function for work with no issue, however any other formatters I install don't show up in NullLsInfo. My guess here is that the default function being empty effectively means nothing is running and it should contain something along the lines of:
```lua
null_ls.register( null_ls.builtins.formatting[source_name] )
```

But then with variations for things that aren't formatters.

Is there a function that should go here or is the default option just not supported?

**Comment by RoryNesbitt** [comment]
Okay so what I've got so far is 
```lua
function(source_name, methods)
  -- All sources with no handler get passed here
  if methods[1] then
    null_ls.register(null_ls.builtins[methods[1]][source_name])
  end
end,
```

Couple things I've noticed that I don't get though:  
Some things have no methods, hence the if statement
This runs for every formatter, including ones that are otherwise specified, resulting in two versions of the same server being added. This is unlike mason-lsp-installer which will only run the default function if there is not a specific one available

**Comment by jay-babu** [comment]
thank you for this. sorry about the miss in documentation.

**Comment by RoryNesbitt** [comment]
No bother, glad to see it merged 😁
