### ISSUE TITLE
Keep getting `mason.nvim/lua/mason-registry/init.lua:67: bad argument #1 to '?' (string expected, got nil)` error in mason.log

### ISSUE THREAD

**Issue by xfzv** [jay-babu/mason-null-ls.nvim#43]
Basically https://github.com/williamboman/mason.nvim/issues/789

I opened the issue in mason repo first because I had no idea `mason-null-ls.nvim` was (apparently?) the culprit.

**Comment by williamboman** [comment]
FWIW [this](https://github.com/williamboman/mason.nvim/blob/6cd678822919b1ed502f9752e3b71ba6a025a7d1/lua/mason-registry/init.lua#L67) is the location. I assumed mason-null-ls.nvim used the `mason-core.log` module but apparently not. Anyways, something in mason-null-ls.nvim might be trying to access a non-existent package.

The error itself is a bit weird though, it seems like the `pcall(require)` is not producing an error message, which it should. I wonder if lazy.nvim's package loader is messing something up. @xfzv does the error occur if you disable lazy.nvim's cache?

```lua
require("lazy").setup(..., {
  performance = {
    cache = { enable = false }
  }
})
```

**Comment by folke** [comment]
It should be `enabled` (forgot the `d`).

Let me know if I can help debug this.

**Comment by jay-babu** [comment]
Apologies for the late reply. I will have to dive into this after the holidays. I currently don't have access to a computer

**Comment by jay-babu** [comment]
https://github.com/jay-babu/mason-null-ls.nvim/blob/main/lua/mason-null-ls/settings.lua#L34-L36

```
        if opts.ensure_installed == nil then 
                 opts.ensure_installed = {} 
         end
```

Can you try adding this to the above location? I think it should fix it.

**Comment by hermitmaster** [comment]
I'm seeing the same issue with both `packer` and `lazy`.

**Comment by jay-babu** [comment]
@xfzv @hermitmaster 

Can you try pinning to this commit? `ab5d99619de2263508abb7fb05ef3a0f24a8d73d`. Possibly the commit right after it is the cause. Sorry for the delay, I still don't have access to a laptop.

**Comment by hermitmaster** [comment]
Pinning to that commit fixed it for me as well.

**Comment by jay-babu** [comment]
I am trying reproduce this and cannot

Minimal config with lazy:
```
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({"git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath})
    vim.fn.system({"git", "-C", lazypath, "checkout", "tags/stable"}) -- last stable release
end
vim.opt.rtp:prepend(lazypath)

-- example using a list of specs with the default options
vim.g.mapleader = " " -- make sure to set `mapleader` before lazy so your mappings are correct

require("lazy").setup(
    {
        {
            "williamboman/mason.nvim",
            config = function()
                require("mason").setup(
                    {
                        ui = {
                            icons = {
                                package_installed = "✓",
                                package_pending = "➜",
                                package_uninstalled = "✗"
                            }
                        }
                    }
                )
            end
        },
        {
            "jose-elias-alvarez/null-ls.nvim",
            config = function()
                require("null-ls").setup()
            end
        },
        {
            "jay-babu/mason-null-ls.nvim",
            config = function()
                require("mason-null-ls").setup({})
            end
        }
    },
    {
        performance = {
            cache = {enabled = false}
        }
    }
)
```

**Comment by hermitmaster** [comment]
It only happens to me in headless mode.

**Comment by hermitmaster** [comment]
No, I’m not certain. I have a shell function that bootstraps a new machine for me and the last step is running `nvim --headless +'Lazy! restore' +'qa'`. I see the errors print to stdout right before it exits.

**Comment by jay-babu** [comment]
> > No, I’m not certain. I have a shell function that bootstraps a new machine for me and the last step is running `nvim --headless +'Lazy! restore' +'qa'`. I see the errors print to stdout right before it exits.
> 
> You can do this to make sure:
> 
> 1. Open Neovim normally from terminal
> 2. Run `:MasonLog`
> 
> Is the error printed in the log that opens?

![image](https://user-images.githubusercontent.com/36803168/210154628-cf26d323-c560-47a6-b80f-f6bef436b166.png)

This is all I see

**Comment by RubixDev** [comment]
I get the same error when running nvim in headless mode with `nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'` and also in `:MasonLog` when normally entering nvim. I do not use `lazy.nvim`

**Comment by jay-babu** [comment]
`nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'`, this command looks wrong right? Mason will continue installing async regardless of `PackerSync`. Maybe creating an `augroup` that fires when installation finishes for everything would be useful. However that error would be different than what is occurring above. Can one of you share your complete dotfiles? I will try to replicate with the exact configuration since it does not seem like I can do so with the minimal config.

I am able to get the below error in headless mode, because `mason` installs packages async detached from `PackerSync` or `Lazy Sync`.

```
jay@Beast:~/.config/nvim$ nvim --headless "+Lazy! sync" +qa
[mason] [INFO  16:34:42] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:120: Executing installer for Package(name=beautysh)
[mason] [INFO  16:34:42] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:120: Executing installer for Package(name=clang-format)
[mason] [INFO  16:34:42] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:120: Executing installer for Package(name=eslint_d)
[mason] [INFO  16:34:42] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:120: Executing installer for Package(name=jsonlint)
[mason.nvim] Neovim is exiting while packages are still installing. Terminating all installations…[mason] [INFO  16:34:43] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:120: Executing installer for Package(name=shellcheck)
[mason] [ERROR 16:34:43] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:159: Installation failed for Package(name=beautysh) error="Installation was aborted."
[mason] [ERROR 16:34:43] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:159: Installation failed for Package(name=clang-format) error="Installation was aborted."
[mason] [ERROR 16:34:43] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:159: Installation failed for Package(name=jsonlint) error="Installation was aborted."
[mason] [ERROR 16:34:43] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:159: Installation failed for Package(name=eslint_d) error="Installation was aborted."
Error detected while processing command line:
[mason.nvim] Neovim exited while the following packages were installing. Installation was aborted.
- beautysh, clang-format, eslint_d, jsonlint, prettier, shellcheck, shfmt, stylua, yamlfmt, yamllint
```

**Comment by jay-babu** [comment]
@williamboman, is there a way to print out the stack trace from where the error is logged? I haven't looked into `mason-core.log` much.

**Comment by williamboman** [comment]
> @williamboman, is there a way to print out the stack trace from where the error is logged? I haven't looked into `mason-core.log` much.

Yeah should be doable via `debug`. I'm not too sure about including stack traces in logs though, will make them too verbose. Let me change the log call that's erroring to be more nil-safe.

Looking into the commit you mentioned, I believe the translation between null-ls and mason names might be a bit too open? There's not always a corresponding package in Mason for a given null-ls source, for example `opacheck` which I see @hermitmaster uses. The hard-coded `-` to `_` (and vice versa) translation might be problematic as well.

**Comment by jay-babu** [comment]
> I'm not too sure about including stack traces in logs though, will make them too verbose.

From my job experiences (which isn't that long), typically when the log level is `error`, a stacktrace is emitted too. For the rest, it's not. At least, it should be available in `:MasonLog`. 

> I believe the translation between null-ls and mason names might be a bit too open? 

It should be fine. There is a check first to see if it is in the registry, if found, then install. Otherwise, it silently skips.

> The hard-coded - to _ (and vice versa) translation might be problematic as well.

There is an override file. First, the logic is to check that file's mapping, if found then install from Mason. If not found, do the implicit mapping and try to install from Mason if same package is available. Otherwise, it silently ignores.

**Comment by jay-babu** [comment]
I am able to reproduce this now regardless of headless installation. @williamboman, is there an api to do something like `has_package`? https://github.com/williamboman/mason.nvim/blob/main/lua/mason-registry/init.lua#L64-L71. I see `get_package` only, which errors when the package is not found. The package not being found in `mason-null-ls` is handled gracefully and is expected behavior. This isn't causing actual issues to users, just logging unnecessarily.

**Comment by jay-babu** [comment]
I guess I can query the table directly: https://github.com/williamboman/mason.nvim/blob/main/lua/mason-registry/index.lua. would you prefer that?

**Comment by williamboman** [comment]
> From my job experiences (which isn't that long), typically when the log level is `error`, a stacktrace is emitted too. For the rest, it's not. At least, it should be available in `:MasonLog`.

Ah I see. So yeah the `log.error` will just log the provided message. You can always log an error message containing a stack trace if you wish, for example by leveraging `xpcall` and `debug.traceback`:

```lua
local log = require "mason-core.log"

local function function_that_errors()
  error("Oh noes.")
end

local ok, err = xpcall(function_that_errors, debug.traceback)

if not ok then
  log.error(err)
end

-- Or without dealing with protected calls:
log.error(debug.traceback("Something weird happened here pls include more info."))
log.info(debug.traceback("Something happened."))

-- Yields
-- [ERROR Wed Jan  4 07:14:38 2023] log.lua:10: log.lua:4: Oh noes.
-- stack traceback:
-- 	[C]: in function 'error'
-- 	log.lua:4: in function <log.lua:3>
-- 	[C]: in function 'xpcall'
--	log.lua:7: in main chunk
```

This approach gives a bit more control and makes the logging a bit simpler, although I agree it would probably make sense to include a stacktrace in all `log.error` calls by default 🤔.

> I am able to reproduce this now regardless of headless installation. @williamboman, is there an api to do something like has_package? https://github.com/williamboman/mason.nvim/blob/main/lua/mason-registry/init.lua#L64-L71. I see get_package only, which errors when the package is not found. The package not being found in mason-null-ls is handled gracefully and is expected behavior. This isn't causing actual issues to users, just logging unnecessarily.

I think that would make sense, added in https://github.com/williamboman/mason.nvim/pull/847!

**Comment by jay-babu** [comment]
Sorry, it took me so long to get to this. I have been away from home and finally got access to a computer: https://github.com/jay-babu/mason-null-ls.nvim/commit/07335008824788725bfa2095e18ddbb527002d63. This should fix it.

**Comment by jay-babu** [comment]
@xfzv @hermitmaster can you confirm?

**Comment by RubixDev** [comment]
For me that fixes it :+1:
