### ISSUE TITLE
Is `setup_handlers()` deprecated?

### ISSUE THREAD

**Issue by UtkarshVerma** [jay-babu/mason-null-ls.nvim#57]
If it's deprecated, then what is the alternative?

**Comment by jay-babu** [comment]
Yes, it is deprecated. The new way is to move them to the setup function under the `handlers` key. I will update the docs later. 

See relevant commit https://github.com/jay-babu/mason-null-ls.nvim/commit/35ce897a8c924b37c0f4ea8789ade6205e347591

**Comment by jay-babu** [comment]
https://github.com/jay-babu/mason-null-ls.nvim/tree/2.0#handlers-usage

2.0 is in the works

**Comment by UtkarshVerma** [comment]
Thanks could you also add a case where `handlers` not being defined in the opts is equivalent to empty `handlers`? This would look better in the config avoiding the need of `handlers = {}` which looks as if it does nothing.

**Comment by jay-babu** [comment]
no, it is not the same. `nil` means do not run handlers

**Comment by UtkarshVerma** [comment]
I would suggest disabling the handlers be a bit explicit. Something like `handlers = false`. Anyhow, this is just my suggestion as a user and you would know better.

**Comment by oyarsa** [comment]
@jay-babu, did you deprecate the function in 1.2 because it will work differently in 2.0? If so, should we keep using `setup_handlers` until 2.0 is out, or is there a workaround?

**Comment by jay-babu** [comment]
> @jay-babu, did you deprecate the function in 1.2 because it will work differently in 2.0? If so, should we keep using `setup_handlers` until 2.0 is out, or is there a workaround?

https://github.com/jay-babu/mason-null-ls.nvim/issues/57#issuecomment-1495271330

**Comment by jay-babu** [comment]
https://github.com/jay-babu/mason-null-ls.nvim/releases/tag/v2.0.0

**Comment by asmodeus812** [comment]
I just love it when breaking api changes like that are made willy-nilly.
