### ISSUE TITLE
duplicate setup of standardrb

### ISSUE THREAD

**Issue by zhengpd** [jay-babu/mason-null-ls.nvim#65]
`nvim-lspconfig` supports `standardrb` as LSP server. If I use automatic setup with `mason-null-ls`, `standardrb` would be setup again using `null-ls.builtins` logic even I do not mean to use standardrb in null-ls.

It might be helpful to mention this behavior on README. I'm using `handlers = { standardrb = function() end }` to avoid the unexpected setup.

**Comment by jay-babu** [comment]
https://github.com/jay-babu/mason-null-ls.nvim#:~:text=function()%20end%2C%20%2D%2D%20disables%20automatic%20setup%20of%20all%20null%2Dls%20sources, it is there?

**Comment by jay-babu** [comment]
https://github.com/jay-babu/mason-null-ls.nvim#handlers-usage

**Comment by zhengpd** [comment]
@jay-babu Yes I saw the disabling part. Just want to point out the behavior when `mason-lspconfig` and `mason-null-ls` support a source in same name.
