### ISSUE TITLE
Why are not all sources supported?

### ISSUE THREAD

**Issue by nieomylnieja** [jay-babu/mason-null-ls.nvim#70]
I see that `lua/mason-null-ls/mappings/filetype.lua` lists all the null-ls supported sources but some of these are commented out, why is that, how do you auto generate this file? I also see that `lua/mason-null-ls/mappings/source.lua` has some custom mappings which don't simply adhere to `-` and `_` substitution, the thing I need in my project is `ansiblelint` which for Mason is `ansible-lint`, and it currently does not work with `ensure_installed`. I'd be happy to help out, just want to know if this is intended, todo or missed? Thanks!

**Comment by nieomylnieja** [comment]
To clarify, passing `ansible-lint` (the Mason way) to `ensure_installed` does work, but then this is not really a bridge, just an install utility :)

**Comment by jay-babu** [comment]
> I see that lua/mason-null-ls/mappings/filetype.lua lists all the null-ls supported sources but some of these are commented out, why is that, how do you auto generate this file?

this file wasn't autogenerated. a contributor had created it. at the time, not many things existed in mason, hence less things are supported.

> I need in my project is ansiblelint which for Mason is ansible-lint, and it currently does not work with ensure_installed.

feel free to add with a PR

**Comment by nieomylnieja** [comment]
It had "-- THIS FILE SHOULD BE GENERATED" hanging at the top, so this was more of a TODO then the current state? :P 

I'll create the PR ;)

**Comment by nieomylnieja** [comment]
Also, some of the things listed there are actually parts of other tools, like `terraform_fmt` is in reality part of `terraformls`, or `pycodestyle` being part of `flake8`.
