### ISSUE TITLE
deno_fmt not autoinstalled

### ISSUE THREAD

**Issue by UtkarshVerma** [jay-babu/mason-null-ls.nvim#73]
Just a minor edge-case I noticed. `deno_fmt` source for null-ls does not  auto-install `deno` through mason.

**Comment by jay-babu** [comment]
please add any overrides needed here: https://github.com/jay-babu/mason-null-ls.nvim/blob/main/lua/mason-null-ls/mappings/source.lua#L7. not really an edge case, just support hasn't been added. `mason-null-ls` attempts to guess the mapping from null-ls to mason, but can't in this case

**Comment by UtkarshVerma** [comment]
Thanks for the info. Could you please add it to the mappings?

**Comment by jay-babu** [comment]
added

**Comment by UtkarshVerma** [comment]
Thanks a lot
