### ISSUE TITLE
Clean readme

### ISSUE THREAD

**Issue by sonjiku** [jay-babu/mason-null-ls.nvim#74]
Hello, you've made very cool projects as extensions to Mason, though I'm finding the readme for this one a bit confusing as it seems like you have copied it from the dap plugin and just changed things arround. I'd appreciate if you ensured everything is correct so it's clear.

**Comment by jay-babu** [comment]
Thanks, what part is unclear?

**Comment by sonjiku** [comment]
Line 145 has a reference to "DAP config".

**Comment by jay-babu** [comment]
done
