### ISSUE TITLE
Future of this plugin with null-ls being archived?

### ISSUE THREAD

**Issue by chrisgrieser** [jay-babu/mason-null-ls.nvim#82]
With null-ls being archived in the near future, and up until now new maintainer in sight, I wanted to ask what the future of this plugin is going to be?

I personally work with three different devices, and I find the `ensure_installed` feature of this plugin immensely useful to ensure I have formatters/linters etc. installed at all devices. 

Will this plugin continue ensuring installation of linters/formatters, even without null-ls? Right now, null-ls is still listed as a requirement for this plugin, but technically, null-ls isn't really needed, since this plugin mainly interfaces with mason to install stuff, right? 🙏

**Comment by chrisgrieser** [comment]
for anyone else finding this issue: I found this plugin, which seems to enable auto-installation as well, and as far as I can tell, it works without null-ls:
https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim

**Comment by catgoose** [comment]
I really like this plugin and I'm wondering if there would be any support for none-ls: https://github.com/nvimtools/none-ls.nvim/issues

**Comment by jay-babu** [comment]
> I really like this plugin and I'm wondering if there would be any support for none-ls: https://github.com/nvimtools/none-ls.nvim

What changes would be needed to support it? I looked at the docs and I don't see anything that needs to change

**Comment by Zeioth** [comment]
I can confirm it works as expected with none-ls

**Comment by daUnknownCoder** [comment]
Bro, Just Replace the `NullLsInstall` with `NoneLsInstall` in the commands, and this plugin is good to go, keepin the name of the repo as mason-null-ls gives the original content antique vibes of null-ls

**Comment by catgoose** [comment]
Thanks, Coach.

**Comment by jay-babu** [comment]
> Bro, Just Replace the `NullLsInstall` with `NoneLsInstall` in the commands, and this plugin is good to go, keepin the name of the repo as mason-null-ls gives the original content antique vibes of null-ls

https://github.com/jay-babu/mason-null-ls.nvim/pull/85, let me know if this gives modern vibes
