### ISSUE TITLE
Future plans given the archiving of null-ls

### ISSUE THREAD

**Issue by EdmundsEcho** [jay-babu/mason-null-ls.nvim#87]
Thank you for integrating null-ls with mason.  The mason ecosystem is clearly improving my workflows, particularly as I transition from my vimscript configurations.

I'm hoping that you might let users know you POV on how to proceed given the dependency of this plugin on a now archived repo.

Thank you!

**Comment by mohamad-supangat** [comment]
another active comunity fork for null is https://github.com/nvimtools/none-ls.nvim

**Comment by jay-babu** [comment]
see https://github.com/jay-babu/mason-null-ls.nvim/issues/82
